[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/blog/:slug"
  to = "/blog/:slug.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/stats"
  to = "/stats.html"
  status = 200